num_iters: -1

optimizer: 'greedy_topk'

k: 100

include_conjugates: false

val_every: 100000 #Don't validate

checkpoint_every: 20 #save checkpoints every n epochs

loss_type: "l2"

likelihood_step_size: 1.0