net_path: "/raid/sr39533/pattern_exp_files/00027-fastMRI_T2_320_brains_whitened-uncond-ddpmpp-edm-gpus3-batch54-fp32-ddpmpp_T2-320-white_64/network-snapshot-010000.pkl"

hard_consistent_output: false

alg_type: "cg"

#default sampling parameters from EDM
defaults:
  - edm_defaults

kwargs:
  cg_lambda: 0.3
  cg_max_iter: 5
  cg_eps: 1e-6
