net_path: "/scratch/04703/sravula/MRI_experiment_files/pattern_exp_files/00031-fastMRI_320-368_knees_whitened-uncond-ddpmpp-edm-gpus3-batch27-fp32-knees_white_320-368_ngf64/network-snapshot-006954.pkl"

alg_type: "dps"

#default sampling parameters from EDM
defaults:
  - edm_defaults

kwargs:
  likelihood_step_size: 2.5
  normalize_grad: true