net_path: "/home/sravula/meta_exp/network-snapshot-003578.pkl"

hard_consistent_output: true

alg_type: "dps"

#default sampling parameters from EDM
defaults:
  - edm_defaults

S_churn: 0.0

kwargs:
  likelihood_step_size: 5.0
  normalize_grad: true
