defaults:
  - data: T2_whitened_brains
  - pattern: 3D_DOGG
  - recon: DPS_brains_whitened
  - training: 3D_DOGG

gpu: 0

save_dir: '/scratch/04703/sravula/sampling_pattern_results/train'

seed: 2024

exp_name: "Brain_DPS"
